server:
  port: 8999

eureka:
  instance:
    hostname: localhost

#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: movie-catalog-service
#          uri: lb://movie-catalog-service
#          predicates:
#            - Path=/catalog/**
#        - id: movie-info-service
#          uri: lb://movie-info-service
#          predicates:
#            - Path=/movies/**
#        - id: ratings-data-service
#          uri: lb://ratings-data-service
#          predicates:
#            - Path=/ratingsdata/**
  
